### ISSUE TITLE
etag problem - argument entity must be string or Buffer

### ISSUE THREAD

**Issue by sercaneraslan** [schickling/gulp-webserver#40]
Hello,

I running gulp-webserver and return this error:

/Users/username/Desktop/project/node_modules/gulp-webserver/node_modules/serve-static/node_modules/send/node_modules/etag/index.js:55
    throw new TypeError('argument entity must be string or Buffer')
          ^
TypeError: argument entity must be string or Buffer
    at etag (/Users/username/Desktop/project/node_modules/gulp-webserver/node_modules/serve-static/node_modules/send/node_modules/etag/index.js:55:11)
    at SendStream.setHeader (/Users/username/Desktop/project/node_modules/gulp-webserver/node_modules/serve-static/node_modules/send/index.js:724:15)
    at SendStream.send (/Users/username/Desktop/project/node_modules/gulp-webserver/node_modules/serve-static/node_modules/send/index.js:500:8)
    at /Users/username/Desktop/project/node_modules/gulp-webserver/node_modules/serve-static/node_modules/send/index.js:630:12
    at Object.oncomplete (fs.js:97:15)

My Gulp File:

var gulp = require('gulp'),
      webserver = require('gulp-webserver');

gulp.task('webserver', function() {
  gulp.src('build')
    .pipe(webserver({
      livereload: true,
      port: 9001,
      open: true
  }));

gulp.task('default', [
    'webserver'
]);

**Comment by luckylooke** [comment]
+1

**Comment by xeecos** [comment]
+1

**Comment by ivankennethwang** [comment]
+1

**Comment by timendez** [comment]
+1
